# This is a basic workflow to help you get started with Actions

name: Unit Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install Eigen
        run: |
          (cd lib/ && git clone --depth 1 https://gitlab.com/libeigen/eigen.git Eigen)
          echo hi
          cmake -Blib/Eigen/build -Hlib/Eigen -DBUILD_TESTING=OFF
          sudo env "PATH=$PATH" cmake --build lib/Eigen/build --target install
      
      - name: Install Epigraph
        run: |
          (cd tests/ && git clone --depth 1 https://github.com/EmbersArc/Epigraph.git Epigraph)
          cmake -Btests/Epigraph/build -Htests/Epigraph -DBUILD_TESTING=OFF -DCATCH_INSTALL_DOCS=OFF -DENABLE_OSQP:BOOL=TRUE -DENABLE_ECOS:BOOL=TRUE
          sudo env "PATH=$PATH" cmake --build tests/Epigraph/build --target install

      # Runs Unit Tests from tests/ folder
      - name: Run Unit Tests
        run: (sh ./.github/workflows/run_tests.sh)

      - name: Code Coverage
        run: bash <(curl -s https://codecov.io/bash)

